######################################################################################################
# +------------------------------------------------------------------------------------------------+ #
# |          ______                 __                     __   ______                   __        | #
# |         / ____/  ___    ____   / /_   _____  ____ _   / /  / ____/  ____ _   _____  / /_       | #
# |        / /      / _ \  / __ \ / __/  / ___/ / __ `/  / /  / /      / __ `/  / ___/ / __/       | #
# |       / /___   /  __/ / / / // /_   / /    / /_/ /  / /  / /___   / /_/ /  / /    / /_         | #
# |       \____/   \___/ /_/ /_/ \__/  /_/     \__,_/  /_/   \____/   \__,_/  /_/     \__/         | #
# |                                                                                                | #
# |                                     www.centralcart.com.br                                     | #
# |                              Monetize o seu servidor de Minecraft                              | #
# +------------------------------------------------------------------------------------------------+ #
######################################################################################################


debug_mode: false